# Generated by Django 3.2.4 on 2021-06-10 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icon', to='book2travel.image')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StructureProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_name', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=32)),
                ('rooms', models.IntegerField(max_length=4)),
                ('services', models.ManyToManyField(to='book2travel.Service')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='structure_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('floor', models.IntegerField(max_length=3)),
                ('number', models.CharField(blank=True, max_length=4)),
                ('start_available', models.DateTimeField()),
                ('end_available', models.DateTimeField()),
                ('price_per_night', models.FloatField()),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_type', to='book2travel.roomtype')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_structure', to='book2travel.structureprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(max_length=1)),
                ('date', models.DateTimeField(default=django.db.models.functions.datetime.Now())),
                ('content', models.TextField()),
                ('structure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_structure', to='book2travel.structureprofile')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer', to='book2travel.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('guests_number', models.IntegerField()),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_structure', to='book2travel.structureprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_user', to='book2travel.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InterestedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_room', to='book2travel.rooms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_user', to='book2travel.userprofile')),
            ],
        ),
    ]
