# Generated by Django 3.2.4 on 2021-06-23 16:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=32)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('overprice', models.FloatField()),
                ('delivery_time', models.DurationField()),
            ],
            options={
                'verbose_name_plural': 'Deliveries',
            },
        ),
        migrations.CreateModel(
            name='EventProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=60)),
                ('brief_description', models.TextField()),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=32)),
                ('province', models.CharField(max_length=2)),
                ('cap', models.CharField(max_length=5)),
                ('country', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=32)),
                ('how_to_reach', models.CharField(max_length=300)),
                ('max_capacity', models.IntegerField()),
                ('seats_available', models.IntegerField(blank=True, default=None, null=True)),
                ('avg_rating', models.FloatField(blank=True, default=None, null=True)),
                ('event_start', models.DateTimeField()),
                ('event_end', models.DateTimeField()),
                ('cancelled', models.BooleanField(default=False)),
                ('artist_list', models.ManyToManyField(to='book2fest.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('row', models.CharField(blank=True, max_length=1)),
                ('number', models.CharField(blank=True, max_length=4)),
                ('price', models.FloatField()),
                ('available', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_event', to='book2fest.eventprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SeatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(upload_to='services', validators=[django.core.validators.FileExtensionValidator(['svg'])])),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_delivery', to='book2fest.delivery')),
                ('seat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_seat', to='book2fest.seat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_user', to='book2fest.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('icon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='icon', to='book2fest.serviceimage')),
            ],
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_type', to='book2fest.seattype'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(null=True)),
                ('date', models.DateTimeField(default=django.db.models.functions.datetime.Now())),
                ('content', models.TextField(null=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_structure', to='book2fest.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='pictures/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pictures', to='book2fest.eventprofile')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=32)),
                ('short_bio', models.CharField(max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_category', to='book2fest.category')),
            ],
        ),
        migrations.AddField(
            model_name='eventprofile',
            name='services',
            field=models.ManyToManyField(to='book2fest.Service'),
        ),
        migrations.AddField(
            model_name='eventprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_user', to='book2fest.organizerprofile'),
        ),
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_genre', to='book2fest.genre'),
        ),
    ]
