# Generated by Django 3.2.4 on 2021-06-17 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book2fest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(upload_to='pictures/')),
            ],
        ),
        migrations.AlterField(
            model_name='picture',
            name='pic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='img', to='book2fest.pic'),
        ),
    ]
