# Generated by Django 3.2.4 on 2021-06-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book2fest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='organizer',
            field=models.BooleanField(default=False),
        ),
    ]
