# Generated by Django 3.2.4 on 2021-06-18 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book2fest', '0002_alter_eventprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_seat', to='book2fest.seat'),
        ),
    ]
