# Generated by Django 3.2.4 on 2021-06-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book2fest', '0002_auto_20210619_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventprofile',
            name='how_to_reach',
            field=models.CharField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non nisl finibus, pharetra diam id, egestas dolor. Donec feugiat elit eu ligula posuere, cursus vestibulum urna laoreet. Sed eros lacus, sollicitudin vitae nisi sed, mattis ornare felis. Phasellus nulla dui, congue a convallis in tellus.', max_length=300),
            preserve_default=False,
        ),
    ]
