# Generated by Django 3.2.4 on 2021-06-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book2fest', '0004_alter_eventprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventprofile',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
