# Generated by Django 3.2.4 on 2021-06-21 13:48

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('book2fest', '0006_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(max_length=1)),
                ('date', models.DateTimeField(default=django.db.models.functions.datetime.Now())),
                ('content', models.TextField()),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_structure', to='book2fest.eventprofile')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer', to='book2fest.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
