# Generated by Django 3.2.4 on 2021-06-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book2fest', '0003_eventprofile_how_to_reach'),
        ('book2fest', '0006_notification'),
    ]

    operations = [
    ]
