# Generated by Django 3.1.7 on 2021-06-15 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book2fest', '0007_auto_20210615_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_user', to='book2fest.organizerprofile'),
        ),
    ]
