# Generated by Django 3.2.4 on 2021-06-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book2fest', '0008_auto_20210622_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventprofile',
            name='avg_rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventprofile',
            name='seats_available',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
