# Generated by Django 3.2.4 on 2021-06-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book2fest', '0009_auto_20210622_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventprofile',
            name='avg_rating',
            field=models.FloatField(null=True),
        ),
    ]
