# Generated by Django 3.1.7 on 2021-06-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book2fest', '0009_auto_20210615_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='path',
            field=models.FilePathField(default="[PosixPath('/mnt/c/Users/maret/Desktop/Scola/III_Anno/II° Semestre/Tecnlogie Web/exam_project/static')]/images/default.png", path="[PosixPath('/mnt/c/Users/maret/Desktop/Scola/III_Anno/II° Semestre/Tecnlogie Web/exam_project/static')]/images/icon"),
        ),
    ]
