# Generated by Django 3.2.4 on 2021-06-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book2fest', '0010_alter_eventprofile_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventprofile',
            name='avg_rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='eventprofile',
            name='seats_available',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
