# Generated by Django 3.2.4 on 2021-06-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book2fest', '0010_alter_review_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(blank=True),
        ),
    ]
