# Generated by Django 3.1.7 on 2021-06-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book2fest', '0010_auto_20210615_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='path',
            field=models.FilePathField(default='/images/default.png', path='/images/icon'),
        ),
    ]
