# Generated by Django 3.2.4 on 2021-06-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book2fest', '0011_auto_20210622_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='pic',
        ),
        migrations.AddField(
            model_name='picture',
            name='img',
            field=models.ImageField(default='green.jpg', upload_to='pictures/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Pic',
        ),
    ]
