# Generated by Django 3.2.4 on 2021-06-22 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book2fest', '0012_auto_20210622_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='writer',
        ),
    ]
